// <auto-generated />
using System;
using CastlePlus2.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace CastlePlus2.Infrastructure.Migrations
{
    [DbContext(typeof(CastlePlus2DbContext))]
    partial class CastlePlus2DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CastlePlus2.Domain.Entities.Rdzen.Nieruchomosc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdEncji");

                    b.Property<Geometry>("Geometria")
                        .HasColumnType("geography");

                    b.Property<long?>("IdAdresuGlownego")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdPodmiotuWlasciciela")
                        .HasColumnType("bigint");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Nieruchomosc", "rdzen");
                });
#pragma warning restore 612, 618
        }
    }
}
