@host = http://localhost:5208
@jwt = REPLACE_WITH_BEARER_TOKEN
@newsId = 00000000-0000-0000-0000-000000000000
@textId = 0

### 1) Create news (admin)
POST {{host}}/api/konfiguracja/zasobyui
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "kodZasobu": "NEWS_HOME_001",
  "typ": "NEWS",
  "kategoria": "HOME",
  "czyAktywny": true,
  "sort": 100,
  "wazneOdUtc": null,
  "wazneDoUtc": null
}

### 2) Add title text
POST {{host}}/api/konfiguracja/zasobyuiteksty
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "idEncji": "{{newsId}}",
  "jezyk": "pl-PL",
  "pole": "Title",
  "wartosc": "Nowa aktualnoœæ",
  "format": "Plain",
  "sort": 0
}

### 3) Add lead text
POST {{host}}/api/konfiguracja/zasobyuiteksty
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "idEncji": "{{newsId}}",
  "jezyk": "pl-PL",
  "pole": "Lead",
  "wartosc": "Krótka zajawka",
  "format": "Plain",
  "sort": 10
}

### 4) Get public news list
GET {{host}}/api/konfiguracja/zasobyui/public?typ=NEWS&kategoria=HOME&jezyk=pl-PL&includeInactive=false

### 5) Update text
PUT {{host}}/api/konfiguracja/zasobyuiteksty/{{textId}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "idZasobuTekstu": {{textId}},
  "idEncji": "{{newsId}}",
  "jezyk": "pl-PL",
  "pole": "Title",
  "wartosc": "Nowa aktualnoœæ (po zmianie)",
  "format": "Plain",
  "sort": 0
}

### 6) Delete text
DELETE {{host}}/api/konfiguracja/zasobyuiteksty/{{textId}}
Authorization: Bearer {{jwt}}

### 7) Delete news
DELETE {{host}}/api/konfiguracja/zasobyui/{{newsId}}
Authorization: Bearer {{jwt}}